name: 42sh

on:
  push:
  pull_request:

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-PSU-200-PAR-2-2-42sh-marouan.bader.git"

jobs:
  check_program_compilation:
    name: Check program compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Make
        run: make
      - name: Make clean
        run: make clean

  push_to_mirror:
    needs: check_program_compilation
    name: Mirror repository
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
